version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:4017"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
